filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /home/Logs/*.log
    # - /path/two
    # - /path/three

# processors:
#   - drop_fields:
#       fields: ["all"]

# output.multiplexer:
#   - output.console:
#       enabled: true
#   - output.logstash:
#       hosts: ["localhost:5044"]

# output:
#   console:
#     enabled: true
#     pretty : true
  # output:
  #   logstash:
  #     hosts: ["logstash:5044"]

# filebeat.outputs:
#   # Output plugin that sends logs to the console
#   console:
#     # Pretty-print the logs to the console
#     pretty: true


#print filebeat output to
output.logstash:
  hosts: ["logstash:5044"]


# ********************* Location of Filebeat Logs Itself ***********************************
# {path.home}/logs  Option -> path.logs
# Config {path.home} -> path.config