filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /home/Logs/*.log
    # - /path/two
    # - /path/three

#print filebeat output to
output.logstash:
  hosts: ["${LOGSTASH_HOST_PORT}"]

logging.level: error
logging.to_files: true
logging.files:
  path: /home/FilebeatLogs
  name: filebeat.log
  rotateeverybytes: 10485760 #10MB
  keepfiles: 7
  permissions: 0644

#================================ HTTP Endpoint ======================================
# Enabled so we can monitor filebeat using filebeat exporter if needed.
# Each beat can expose internal metrics through a HTTP endpoint. For security
# reasons the endpoint is disabled by default. This feature is currently experimental.
# Stats can be access through http://localhost:5066/stats . For pretty JSON output
# append ?pretty to the URL.

# Defines if the HTTP endpoint is enabled.
http.enabled: true
http.host: 0.0.0.0
http.port: 5066

# processors:
#   - drop_fields:
#       fields: ["all"]

# output.multiplexer:
#   - output.console:
#       enabled: true
#   - output.logstash:
#       hosts: ["localhost:5044"]

# output:
#   console:
#     enabled: true
#     pretty : true
  # output:
  #   logstash:
  #     hosts: ["logstash:5044"]

# filebeat.outputs:
#   # Output plugin that sends logs to the console
#   console:
#     # Pretty-print the logs to the console
#     pretty: true


# ********************* Location of Filebeat Logs Itself ***********************************
# {path.home}/logs  Option -> path.logs
# Config {path.home} -> path.config