version: '3.5'

# will contain all filebeat data.
volumes:
  LOG_DIR:

services:
  #Python Logs Shipper
  filebeat:
    container_name: filebeat
    hostname: filebeat
    command: ./init.sh
    user: root
    build:
      context: filebeat/
      dockerfile: Dockerfile
      args:
        ELK_VERSION : ${ELK_VERSION}
        # - ELASTICSEARCH_HOST=elasticsearch
        # - ELASTICSEARCH_PORT=9200
    environment:
      - LOGSTASH_HOST_PORT=${LOGSTASH_HOST_PORT}
    ports:
      - "5066:5066"
    restart: always
    volumes:
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ${LOG_DIR}:/home/Logs/:rw