version: '3.5'

services:
  logstash:
    container_name: logstash
    hostname: logstash
    build:
      context: logstash/
      dockerfile: Dockerfile
      args:
        ELK_VERSION : ${ELK_VERSION}
    restart: always
    environment:
      - ELASTICSEARCH_HOST_PORT=${ELASTICSEARCH_HOST_PORT}
      # - LS_JAVA_OPTS="-Xms1024m -Xmx1024m"
      - LS_OPTS="--config.reload.automatic"
      # - LS_OPTS="--config.reload.automatic --config.reload.interval 20"

    volumes:
      - ./logstash/pipeline/:/usr/share/logstash/pipeline/:ro,Z
    ports:
      - "5044:5044"   # Open port for Filebeat
      - "9600:9600"  # Open port for logstash